package com.mouglotte.specy;

public enum DecisionType {

	// Besoins
	NEED_HUNGER, NEED_REST, NEED_SOCIAL, NEED_FUN,
//	SEARCHING_NEED_HUNGER, 
//	SEARCHING_NEED_REST, 
//	SEARCHING_NEED_SOCIAL, 
//	SEARCHING_NEED_FUN,
//	FULFILLING_NEED_HUNGER, 
//	FULFILLING_NEED_REST, 
//	FULFILLING_NEED_SOCIAL, 
//	FULFILLING_NEED_FUN,
	// Envies
	DESIRE_HUNGER, DESIRE_REST, DESIRE_SOCIAL, DESIRE_FUN, DESIRE_LOVE, DESIRE_FIGHT, DESIRE_WORK;
}
